spring:
  application:
    name: saltu-user
  datasource:
    url: jdbc:mysql://localhost:3306/saltu_db
    username: root
    password: amlayes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

snowflake:
  dataCenterId: 1
  machineId: 1

jwt:
  config:
    secretKey: saltu
    ttl: 604800000 # 7 days
    prefix: Bearer