spring:
  application:
    name: saltu-zuul
  datasource:
    url: jdbc:mysql://localhost:3306/saltu_db
    username: root
    password: amlayes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

snowflake:
  dataCenterId: 1
  machineId: 1

jwt:
  config:
    secretKey: saltu
    ttl: 604800000 # 7 days
    prefix: Bearer

zuul:
  routes:
    saltu-user:
      path: /member/**
      serviceId: saltu-user
      strip-prefix: false
    saltu-oauth:
      path: /oauth/**
      serviceId: saltu-user
      strip-prefix: false
    saltu-login:
      path: /login
      serviceId: saltu-user
      strip-prefix: false
    saltu-post:
      path: /post/**
      serviceId: saltu-post
      strip-prefix: false
