spring:
  application:
    name: saltu-post
  datasource:
    url: jdbc:mysql://localhost:3306/saltu_db
    username: root
    password: amlayes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9002

snowflake:
  dataCenterId: 2
  machineId: 1

jwt:
  config:
    secretKey: saltu
    ttl: 604800000 # 7 days
    prefix: Bearer