spring:
  application:
    name: saltu-post
  datasource:
    url: jdbc:mysql://localhost:3306/saltu_db
    username: root
    password: amlayes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/yvo11/Workplace/saltu_upload/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9102

snowflake:
  dataCenterId: 2
  machineId: 1

jwt:
  config:
    secretKey: saltu
    ttl: 604800000 # 7 days
    prefix: Bearer

upload:
  path: /home/yvo11/Workplace/saltu_upload
